apiVersion: apps/v1

kind: Deployment
metadata:
  name: so
spec:
  selector:
    matchLabels:
      app: so
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: so
    spec:
      containers:
        - name: so
          image: so:4.0
